OnlineShop/home/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.Home.as_view(), name='home'),
]

OnlineShop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('order/', include('order.urls', namespace='order')),
    path('zarinpal/', include('zarinpal.urls', namespace='zarinpal')),
    path('product/', include('product.urls', namespace='product')),
    path('api_product/', include('product.urls', namespace='api_product')),
    path('api_accounts/', include('accounts.urls', namespace='api_accounts')),
    path('', include('home.urls',)),
    path('', include('api.urls',)),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views
from rest_framework.authtoken import views as auth_token
from rest_framework import routers


app_name = 'accounts'

urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='user_register'),
    path('verify/', views.UserRegisterVerifyCodeView.as_view(), name='verify_code'),
    path('login/', views.UsreLoginView.as_view(), name='user_login'),
    path('logout/', views.UserLogoutView.as_view(), name='user_logout'),
    path('address/', views.UserAddress.as_view(), name='user_address'),
    path('choice/', views.ChoiceAddress.as_view(), name='choice_address'),
    path('edit/', views.EditProfile.as_view(), name='edit_profile'),
    path('my_order/', views.MyOrder.as_view(), name='my_order'),
    path('user/', views.UserCreateView.as_view(), name='user-list-create'),
    path('hello/', views.HelloView.as_view(), name='hello'),
    path('api-token-auth/', auth_token.obtain_auth_token),
]

router = routers.SimpleRouter()
router.register('user', views.UserViewSet)
urlpatterns += router.urls

api/urls.py
from django.urls import path
from rest_framework import routers
from rest_framework.authtoken import views as auth_token
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

from api import views


app_name = 'api'

urlpatterns = [
    path('api-token-auth/', auth_token.obtain_auth_token),
    path('comment/', views.CommentView.as_view()),
    path('schema/', SpectacularAPIView.as_view(), name='schema'),
    path('swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
]

router = routers.SimpleRouter()
router.register('user', views.UserViewSet)
router.register('address', views.AddressViewSet)
router.register('order', views.OrderViewSet)
urlpatterns += router.urls

home/urls.py
from django.urls import path
from . import views
from product.views import *

app_name = 'home'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('contact/', views.Contact.as_view(), name='contact'),
    path('about/', views.About.as_view(), name='about'),
    path('details/', ProductDetail.as_view(), name='details'),
    path('profile/', UserProfile.as_view(), name='profile'),
]

order/urls.py
from django.urls import path
from . import views
from rest_framework import routers


app_name = 'order'

urlpatterns = [
    path('cart/', views.CartView.as_view(), name='shopping-cart'),
    path('cart/add/<int:product_id>/', views.CartAddView.as_view(), name='cart_add'),
    path('cart/del/<int:product_id>/', views.CartDelView.as_view(), name='cart_del'),
    path('checkout/', views.Checkout.as_view(), name='checkout'),
    path('paid/', views.Paid.as_view(), name='paid'),
]

router = routers.SimpleRouter()
router.register('orders', views.OrderViewSet)
urlpatterns += router.urls

product/urls.py
from django.urls import path
from .views import *

app_name = 'product'

urlpatterns = [
    path('api_product/', ProductCreateView.as_view(), name='product-list-create'),
    path('', Products.as_view(), name='shop'),
    path('category/<slug:category_slug>/', Products.as_view(), name='category_filter'),
    path('search_product', SearchProduct.as_view(), name='search_product'),
    path('comments/<int:pk>/', CommentView.as_view(), name='product_comment'),
    path('comments/', CommentView.as_view(), name='product_comment'),
    path('detail/<int:product_id>', ProductDetail.as_view(), name='product_detail'),
]

home/forms.py
from django import forms


class ContactForm(forms.Form):
    name = forms.CharField(max_length=100)
    email = forms.EmailField()
    text = forms.CharField(max_length=255)

home/views.py
from django.shortcuts import render, redirect
from django.views import View
from .forms import ContactForm
from OnlineShop import settings
from django.core.mail import BadHeaderError, send_mail
from django.http import HttpResponse, HttpResponseRedirect
import logging
from order.models import OrderItems
from product.models import Product
from django.db.models import Count
from django.shortcuts import get_object_or_404


"""
This view is responsible for displaying dynamic content on the homepage,
 including the most ordered product and the latest products. It calculates
   this information by querying the database and then renders the 
   'index.html' template with the appropriate data.
"""
class Home(View):
    template_name = 'index.html'

    def get(self, request):
        product_counts = OrderItems.objects.values('product').annotate(total_quantity=Count('product__id'))
        most_ordered_product = get_object_or_404(Product, id=product_counts.order_by('-total_quantity').first()['product'])
        # most_ordered_product = Product.objects.get(id=product_counts.order_by('-total_quantity').first()['product'])
        last_products = Product.objects.all().order_by('-id')[:3]
        return render(request, self.template_name, {'most_ordered_product': most_ordered_product, 'last_products': last_products})


class Contact(View):
    template_name = 'contact.html'

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):
        form = ContactForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            message = form.cleaned_data['text']
            subject = 'contact us,'
            message = f'{name}\n{email}\n{message}'
            email_from = settings.EMAIL_HOST_USER
            try:
                send_mail(subject,message,email_from,["cafeshopproject098@gmail.com"],fail_silently=False,)
                return render(request, self.template_name)
            except BadHeaderError:
                return HttpResponse("Invalid header found.")
        else:
            print('form not valid...')
        return render(request, self.template_name)


class About(View):
    template_name = 'about.html'

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):
        pass

home/templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="zxx">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Male_Fashion Template">
    <meta name="keywords" content="Male_Fashion, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Male-Fashion | Template</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@300;400;600;700;800;900&display=swap"
    rel="stylesheet">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <!-- Css Styles -->
    <link rel="stylesheet" href="{% static 'home/css/bootstrap.min.css' %}" rel="stylesheet"> 
    <link rel="stylesheet" href="{% static 'home/css/font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'home/css/elegant-icons.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'home/css/magnific-popup.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'home/css/nice-select.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'home/css/owl.carousel.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'home/css/slicknav.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'home/css/style.css' %}" type="text/css">
</head>

<body>
   {% include 'inc/Header.html' %}
   {% include 'inc/hero.html' %}
   <br><br>
   {% include 'inc/product.html' %}
   {% include 'inc/banner.html' %}
   {% include 'inc/latest.html' %}
   {% include 'inc/instagram.html' %}
   <br><br>
   {% include 'inc/footer.html' %}
   

<!-- Js Plugins -->
<script src="{% static 'home/js/jquery-3.3.1.min.js'%}"></script>
<script src="{% static 'home/js/bootstrap.min.js'%}"></script>
<script src="{% static 'home/js/jquery.nice-select.min.js'%}"></script>
<script src="{% static 'home/js/jquery.nicescroll.min.js'%}"></script>
<script src="{% static 'home/js/jquery.magnific-popup.min.js'%}"></script>
<script src="{% static 'home/js/jquery.countdown.min.js'%}"></script>
<script src="{% static 'home/js/jquery.slicknav.js'%}"></script>
<script src="{% static 'home/js/mixitup.min.js'%}"></script>
<script src="{% static 'home/js/owl.carousel.min.js'%}"></script>
<script src="{% static 'home/js/main.js'%}"></script>
 
</body>

</html>

home/templates/shop.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Male_Fashion Template">
    <meta name="keywords" content="Male_Fashion, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Male-Fashion | Template</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@300;400;600;700;800;900&display=swap"
    rel="stylesheet">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <!-- Css Styles -->
    <link rel="stylesheet" href="{% static 'home/css/bootstrap.min.css' %}" rel="stylesheet"> 
    <link rel="stylesheet" href="{% static 'home/css/font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'home/css/elegant-icons.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'home/css/magnific-popup.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'home/css/nice-select.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'home/css/owl.carousel.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'home/css/slicknav.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'home/css/style.css' %}" type="text/css">
</head>

<body>

    {% include 'inc/Header.html' %}

    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-option">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb__text">
                        <h4>Shop</h4>
                        <div class="breadcrumb__links">
                            <a href="./index.html">Home</a>
                            <span>Shop</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- Shop Section Begin -->
    <section class="shop spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="shop__sidebar">
                        <div class="shop__sidebar__search">
                            <form class="d-flex" action="{% url 'product:search_product' %}">
                                <input class="form-control me-2" type="search" name="search_product" placeholder="Search" aria-label="Search">
                                <button class="btn btn-outline-success" type="submit">Search</button>
                            </form>
                        </div>
                        <div class="shop__sidebar__accordion">
                            <div class="accordion" id="accordionExample">
                                <div class="card">
                                    <div class="card-heading">
                                        <a data-toggle="collapse" data-target="#collapseOne">Categories</a>
                                    </div>
                                    <div id="collapseOne" class="collapse show" data-parent="#accordionExample">
                                        <div class="card-body">
                                            <div class="shop__sidebar__categories">
                                                <ul class="nice-scroll">
                                                    {% for category in categories %}
                                                    <div class="btn-group">
                                                        <a href="{{ category.get_absolute_url }}" class="btn btn-white">{{ category.name }}</a>
                                                        
                                                    </div>
                                                    <br>
                                                    {% endfor %}
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="card">
                                    <div class="card-heading">
                                        <a data-toggle="collapse" data-target="#collapseTwo">Branding</a>
                                    </div>
                                    <div id="collapseTwo" class="collapse show" data-parent="#accordionExample">
                                        <div class="card-body">
                                            <div class="shop__sidebar__brand">
                                                <ul>
                                                    {% for brand in brands %}
                                                        <li><a href="#">{{ brand.name }}</a></li>
                                                    {% endfor %}
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>    
                                <div class="card">
                                    <div class="card-heading">
                                        <a data-toggle="collapse" data-target="#collapseSix">Tags</a>
                                    </div>
                                    <div id="collapseSix" class="collapse show" data-parent="#accordionExample">
                                        <div class="card-body">
                                            <div class="shop__sidebar__tags">
                                                <a href="#">Product</a>
                                                <a href="#">Bags</a>
                                                <a href="#">Shoes</a>
                                                <a href="#">Fashio</a>
                                                <a href="#">Clothing</a>
                                                <a href="#">Hats</a>
                                                <a href="#">Accessories</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-9">
                    <div class="shop__product__option">
                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-sm-6">
                                <div class="shop__product__option__left">
                                    <p>Showing 1–12 of 126 results</p>
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-6">
                                <div class="shop__product__option__right">
                                    <p>Sort by Price:</p>
                                    <select>
                                        <option value="">Low To High</option>
                                        <option value="">$0 - $55</option>
                                        <option value="">$55 - $100</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                        <div class="row">
                            {% for product in serializers %}
                            <div class="col-lg-4 col-md-6 col-sm-6 col-sm-6">
                                <div class="shadow p-3 mb-5 bg-white rounded">
                                <div class="product__item">
                                    <div class="product__item__pic set-bg" data-setbg="{{ product.image }}">
                                        <ul class="product__hover">
                                            <li><a href="#"><img src="{% static 'home/img/icon/heart.png' %}" alt=""></a></li>
                                            <li><a href="#"><img src="{% static 'home/img/icon/compare.png' %}" alt=""></a></li>
                                            <li><a href="#"><img src="{% static 'home/img/icon/search.png' %}" alt=""></a></li>
                                        </ul>
                                    </div>
                                    <div class="product__item__text">
                                        <a href="{% url 'product:product_detail' product.id %}"><h6>{{ product.name }} </h6></a>
                                        {% if request.user.is_authenticated %}
                                            <form method="post" action="{% url 'order:cart_add' product.id %}">
                                                {% csrf_token %}
                                                {{ form }}
                                                <input href="#" type="submit" value="+ Add To Cart" >
                                            </form>
                                        {% else %}
                                            <a href="{% url 'accounts:user_login' %}" >Login first</a>
                                        {% endif %}
                                        <div class="rating">
                                            <i class="fa fa-star-o"></i>
                                            <i class="fa fa-star-o"></i>
                                            <i class="fa fa-star-o"></i>
                                            <i class="fa fa-star-o"></i>
                                            <i class="fa fa-star-o"></i>
                                        </div>
                                        <h5>price .{{ product.price }} $</h5>
                                        {% if product.number < 4 %}
                                        <h5>left over .{{ product.number }}</h5>
                                        {% else %}
                                        <h5> .</h5>
                                        {% endif %}
                                    </div>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                    
                            <nav aria-label="Page navigation example">
                                <ul class="pagination ">
                                    {% if serializers.has_previous %}
                                    <li class="page-item"><a class="page-link" href="?page=1">First</a></li>
                                    <li class="page-item"><a class="page-link" href="?page={{ serializers.previous_page_number }}">{{ serializers.previous_page_number }}</a></li>
                                    {% endif %}
                   
                                    {% if serializers.has_next %}
                                    <li class="page-item"><a class="page-link" href="?page={{ serializers.next_page_number }}">{{ serializers.next_page_number }}</a></li>
                                    <li class="page-item"><a class="page-link" href="?page={{ serializers.paginator.num_pages }}">Last</a></li>
                                    {% endif %}
                                </ul>
                              </nav>
                        </div>
            </div>
        </div>
    </section>
    <!-- Shop Section End -->

    <!-- Footer Section Begin -->
    <footer class="footer">
        <div class="container">
            
                
            
        </div>
    </footer>
    <!-- Footer Section End -->

    <!-- Search Begin -->
    <div class="search-model">
        <div class="h-100 d-flex align-items-center justify-content-center">
            <div class="search-close-switch">+</div>
            <form class="search-model-form">
                <input type="text" id="search-input" placeholder="Search here.....">
            </form>
        </div>
    </div>
    <!-- Search End -->

    <!-- Js Plugins -->
    
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    
    <script src="{% static 'home/js/jquery-3.3.1.min.js'%}"></script>
    <script src="{% static 'home/js/bootstrap.min.js'%}"></script>
    <script src="{% static 'home/js/jquery.nice-select.min.js'%}"></script>
    <script src="{% static 'home/js/jquery.nicescroll.min.js'%}"></script>
    <script src="{% static 'home/js/jquery.magnific-popup.min.js'%}"></script>
    <script src="{% static 'home/js/jquery.countdown.min.js'%}"></script>
    <script src="{% static 'home/js/jquery.slicknav.js'%}"></script>
    <script src="{% static 'home/js/mixitup.min.js'%}"></script>
    <script src="{% static 'home/js/owl.carousel.min.js'%}"></script>
    <script src="{% static 'home/js/main.js'%}"></script>
 
</body>

</html>

home/templates/shopping-cart.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Male_Fashion Template">
    <meta name="keywords" content="Male_Fashion, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Male-Fashion | Template</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@300;400;600;700;800;900&display=swap"
    rel="stylesheet">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <!-- Css Styles -->
    <link rel="stylesheet" href="{% static 'home/css/bootstrap.min.css' %}" rel="stylesheet"> 
    <link rel="stylesheet" href="{% static 'home/css/font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'home/css/elegant-icons.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'home/css/magnific-popup.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'home/css/nice-select.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'home/css/owl.carousel.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'home/css/slicknav.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'home/css/style.css' %}" type="text/css">
</head>

<body>
    {% include 'inc/Header.html' %}

    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-option">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb__text">
                        <h4>Shopping Cart</h4>
                        <div class="breadcrumb__links">
                            <a href="./index.html">Home</a>
                            <a href="./shop.html">Shop</a>
                            <span>Shopping Cart</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- Shopping Cart Section Begin -->
    <section class="shopping-cart spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="shopping__cart__table">
                        <table class="table">
                            <thead>
                              <tr>
                                <th scope="col">#</th>
                                <th scope="col">product</th>
                                <th scope="col">price</th>
                                <th scope="col">quantity</th>
                                <th scope="col">total price</th>
                              </tr>
                            </thead>
                            <tbody>
                                {% for item in cart %}
                                    <tr>
                                        <th scope="row">{{ forloop.counter }}<img src="{{ item.product.image.url }}" width="50px" style="border-radius: 50%;"></th>
                                        <td>{{ item.product }}</td>
                                        <td>{{ item.price }}</td>
                                        <td>{{ item.quantity }}</td>
                                        <td>{{ item.total_price }}</td>
                                        <td class="cart__close"><a href="{% url 'order:cart_del' item.product.id %}" class="fa fa-close"></a></td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                          </table>
                        
                    </div>
                    <div class="row">
                        <div class="col-lg-6 col-md-6 col-sm-6">
                            <div class="continue__btn update__btn">
                                <a href="{% url 'product:shop' %}">Continue Shopping</a>
                            </div>
                        </div>
                       
                    </div>
                </div>
                <!-- Cart Total Section Begin -->
                <div class="col-lg-4">
                    <div class="cart__discount">
                        <h6>Discount codes</h6>
                        <form method ="post" action="">
                            {% csrf_token %}
                            <input  name="coupon" type="text" placeholder="Coupon code">
                            <a href="{% url 'order:checkout' %}" type="submit" class="primary-btn">Apply</a>
                        </form>
                    </div>
                    <div class="cart__total">
                        <h6>Cart total</h6>
                        <ul>
                            <li>Subtotal <span id="subtotal">{{ cart.get_total_price }}</span></li>
                            <li>Total <span id="total">{{ cart.get_total_price }}</span></li>
                        </ul>
                        {% if request.user.is_authenticated %}
                        <a href="{% url 'order:checkout' %}" class="primary-btn">Proceed to checkout</a>
                        {% else %}
                        <a href="{% url 'accounts:user_login' %}" class="primary-btn">Login first</a>
                        {% endif %}
                    </div>
                </div>
                <!-- Cart Total Section End -->

            </div>
        </div>
    </section>
    <!-- Shopping Cart Section End -->

    <!-- Footer Section Begin -->
    <footer class="footer">
        <div class="row">
            <div class="col-lg-12 text-center">
                <div class="footer__copyright__text">
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    <p>Copyright ©
                        <script>
                            document.write(new Date().getFullYear());
                        </script>-2020
                        This online store template was created<i class="fa fa-heart-o"
                        aria-hidden="true"></i> by <a href="https://github.com/Abbas-moradi" target="_blank">Abbas Moradi</a>
                    </p>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </div>
            </div>
        </div>
    </footer>
    <!-- Footer Section End -->

    <!-- Search Begin -->
    <div class="search-model">
        <div class="h-100 d-flex align-items-center justify-content-center">
            <div class="search-close-switch">+</div>
            <form class="search-model-form">
                <input type="text" id="search-input" placeholder="Search here.....">
            </form>
        </div>
    </div>
    <!-- Search End -->


    <!-- Js Plugins -->
    
    <script src="{% static 'home/js/jquery-3.3.1.min.js'%}"></script>
    <script src="{% static 'home/js/bootstrap.min.js'%}"></script>
    <script src="{% static 'home/js/jquery.nice-select.min.js'%}"></script>
    <script src="{% static 'home/js/jquery.nicescroll.min.js'%}"></script>
    <script src="{% static 'home/js/jquery.magnific-popup.min.js'%}"></script>
    <script src="{% static 'home/js/jquery.countdown.min.js'%}"></script>
    <script src="{% static 'home/js/jquery.slicknav.js'%}"></script>
    <script src="{% static 'home/js/mixitup.min.js'%}"></script>
    <script src="{% static 'home/js/owl.carousel.min.js'%}"></script>
    <script src="{% static 'home/js/main.js'%}"></script>
 
</body>

</html>