OnlineShop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('order/', include('order.urls', namespace='order')),
    path('zarinpal/', include('zarinpal.urls', namespace='zarinpal')),
    path('product/', include('product.urls', namespace='product')),
    path('api_product/', include('product.urls', namespace='api_product')),
    path('api_accounts/', include('accounts.urls', namespace='api_accounts')),
    path('', include('home.urls',)),
    path('', include('api.urls',)),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views
from rest_framework.authtoken import views as auth_token
from rest_framework import routers


app_name = 'accounts'

urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='user_register'),
    path('verify/', views.UserRegisterVerifyCodeView.as_view(), name='verify_code'),
    path('login/', views.UsreLoginView.as_view(), name='user_login'),
    path('logout/', views.UserLogoutView.as_view(), name='user_logout'),
    path('address/', views.UserAddress.as_view(), name='user_address'),
    path('choice/', views.ChoiceAddress.as_view(), name='choice_address'),
    path('edit/', views.EditProfile.as_view(), name='edit_profile'),
    path('my_order/', views.MyOrder.as_view(), name='my_order'),
    path('user/', views.UserCreateView.as_view(), name='user-list-create'),
    path('hello/', views.HelloView.as_view(), name='hello'),
    path('api-token-auth/', auth_token.obtain_auth_token),
]

router = routers.SimpleRouter()
router.register('user', views.UserViewSet)
urlpatterns += router.urls

api/urls.py
from django.urls import path
from rest_framework import routers
from rest_framework.authtoken import views as auth_token
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

from api import views


app_name = 'api'

urlpatterns = [
    path('api-token-auth/', auth_token.obtain_auth_token),
    path('comment/', views.CommentView.as_view()),
    path('schema/', SpectacularAPIView.as_view(), name='schema'),
    path('swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
]

router = routers.SimpleRouter()
router.register('user', views.UserViewSet)
router.register('address', views.AddressViewSet)
router.register('order', views.OrderViewSet)
urlpatterns += router.urls

home/urls.py
from django.urls import path
from . import views
from product.views import *

app_name = 'home'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('contact/', views.Contact.as_view(), name='contact'),
    path('about/', views.About.as_view(), name='about'),
    path('details/', ProductDetail.as_view(), name='details'),
    path('profile/', UserProfile.as_view(), name='profile'),
]

order/urls.py
from django.urls import path
from . import views
from rest_framework import routers


app_name = 'order'

urlpatterns = [
    path('cart/', views.CartView.as_view(), name='shopping-cart'),
    path('cart/add/<int:product_id>/', views.CartAddView.as_view(), name='cart_add'),
    path('cart/del/<int:product_id>/', views.CartDelView.as_view(), name='cart_del'),
    path('checkout/', views.Checkout.as_view(), name='checkout'),
    path('paid/', views.Paid.as_view(), name='paid'),
]

router = routers.SimpleRouter()
router.register('orders', views.OrderViewSet)
urlpatterns += router.urls

product/urls.py
from django.urls import path
from .views import *

app_name = 'product'

urlpatterns = [
    path('api_product/', ProductCreateView.as_view(), name='product-list-create'),
    path('', Products.as_view(), name='shop'),
    path('category/<slug:category_slug>/', Products.as_view(), name='category_filter'),
    path('search_product', SearchProduct.as_view(), name='search_product'),
    path('comments/<int:pk>/', CommentView.as_view(), name='product_comment'),
    path('comments/', CommentView.as_view(), name='product_comment'),
    path('detail/<int:product_id>', ProductDetail.as_view(), name='product_detail'),
]

product/models.py
from django.db import models
from accounts.models import User
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True)
    image = models.ImageField(upload_to='category/%Y/%m/%d/', blank=True)
    status = models.BooleanField(default=True)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, related_name='children', null=True, blank=True)
    is_child = models.BooleanField(default=False)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return reverse('category_filter', args=[self.slug,])
    
    def __str__(self) -> str:
        return self.name
    

class Brand(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, unique=True)
    status = models.BooleanField(default=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'brand'
        verbose_name_plural = 'brands'

    def __str__(self) -> str:
        return self.name


class Product(models.Model):
    category = models.ManyToManyField(Category, related_name='products')
    name = models.CharField(max_length=100)
    description = models.TextField()
    price = models.IntegerField()
    number = models.PositiveSmallIntegerField()
    available = models.BooleanField(default=True)
    discount = models.IntegerField()
    image = models.ImageField(upload_to='product/%Y/%m/%d/')
    created = models.DateTimeField(auto_now=True)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)

    class Meta:
        ordering = ('name',)

    def __str__(self) -> str:
        return self.name


class ProductImage(models.Model):
    product_id = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='product_img')
    image = models.ImageField(upload_to='product/%Y/%m/%d/')
    status = models.BooleanField(default=True)

    class Meta:
        ordering = ('product_id',)

    def __str__(self) -> str:
        return str(self.product_id)


class Comment(models.Model):
    product_id = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='product_cmnt')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    description = models.TextField()
    status = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('product_id',)
        verbose_name = 'comment'
        verbose_name_plural = 'comments'

home/forms.py
from django import forms


class ContactForm(forms.Form):
    name = forms.CharField(max_length=100)
    email = forms.EmailField()
    text = forms.CharField(max_length=255)

product/forms.py
from django import forms


class UserComment(forms.Form):
    title = forms.CharField(max_length=100)
    description = forms.CharField(widget=forms.Textarea)

home/views.py
from django.shortcuts import render, redirect
from django.views import View
from .forms import ContactForm
from OnlineShop import settings
from django.core.mail import BadHeaderError, send_mail
from django.http import HttpResponse, HttpResponseRedirect
import logging
from order.models import OrderItems
from product.models import Product
from django.db.models import Count
from django.shortcuts import get_object_or_404


"""
This view is responsible for displaying dynamic content on the homepage,
 including the most ordered product and the latest products. It calculates
   this information by querying the database and then renders the 
   'index.html' template with the appropriate data.
"""
class Home(View):
    template_name = 'index.html'

    def get(self, request):
        product_counts = OrderItems.objects.values('product').annotate(total_quantity=Count('product__id'))
        most_ordered_product = get_object_or_404(Product, id=product_counts.order_by('-total_quantity').first()['product'])
        # most_ordered_product = Product.objects.get(id=product_counts.order_by('-total_quantity').first()['product'])
        last_products = Product.objects.all().order_by('-id')[:3]
        return render(request, self.template_name, {'most_ordered_product': most_ordered_product, 'last_products': last_products})


class Contact(View):
    template_name = 'contact.html'

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):
        form = ContactForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            message = form.cleaned_data['text']
            subject = 'contact us,'
            message = f'{name}\n{email}\n{message}'
            email_from = settings.EMAIL_HOST_USER
            try:
                send_mail(subject,message,email_from,["cafeshopproject098@gmail.com"],fail_silently=False,)
                return render(request, self.template_name)
            except BadHeaderError:
                return HttpResponse("Invalid header found.")
        else:
            print('form not valid...')
        return render(request, self.template_name)


class About(View):
    template_name = 'about.html'

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):
        pass

product/views.py
from django.shortcuts import render
from rest_framework.response import Response
from rest_framework.views import APIView
from .models import Product, Category, Brand, Comment, ProductImage
from .serializers import ProductSerializer, CategorySerializer, BrandSerializer, CommentSerializer
from django.views import View
from order.forms import CartAddForm
from django.views.generic import ListView
from django.views.decorators.cache import cache_page
from django.utils.decorators import method_decorator
from rest_framework.permissions import IsAuthenticated, IsAdminUser
from rest_framework import status
from permissions import IsOwnerOrReadOnly
from order.models import Order, OrderItems
from django.shortcuts import get_object_or_404
from product.models import Comment
from django.core.paginator import Paginator
from .forms import UserComment 


class ProductCreateView(APIView):
    permission_classes = [IsAuthenticated]

    def get(self, request):
        queryset = Product.objects.all()
        serializer_class = ProductSerializer(instance=queryset, many=True)
        return Response(serializer_class.data)


"""
This view is intended to display a list of products with optional
category filtering, and it uses caching to improve performance by
serving cached HTML content when appropriate.
"""
class Products(View):
    template_name = 'shop.html'

    @method_decorator(cache_page(60 * 15))
    def get(self, request, category_slug=None):
        form = CartAddForm()
        product_queryset = Product.objects.filter(available=True)
        serializer_class_product = ProductSerializer(instance=product_queryset, many=True)
        category_queryset = Category.objects.filter(is_child=False, status=True)
        serializer_class_category = CategorySerializer(instance=category_queryset, many=True)
        brand_queryset = Brand.objects.all()
        serializer_class_brand = BrandSerializer(instance=brand_queryset, many=True)
        
        if category_slug:
            category_queryset = Category.objects.get(slug=category_slug)
            product_queryset = product_queryset.filter(category=category_queryset)
            serializer_class_product = ProductSerializer(instance=product_queryset, many=True)
        
        pagination = Paginator(serializer_class_product.data, 3)
        page_number = request.GET.get('page')
        page_object = pagination.get_page(page_number)

        return render(request, self.template_name, {
            "serializers": page_object,
            "categories": serializer_class_category.data,
            "brands": serializer_class_brand.data,
            "form": form
            })

    
class UserProfile(View):
    template_name = 'profile.html'

    def get(self, request):
        last_order = Order.objects.filter(user=request.user).latest('order_date')
        order_item = OrderItems.objects.filter(order=last_order)

        return render(request, self.template_name, {'last_order': last_order, 'orders': order_item})
    

"""
In summary, this view is designed to handle search functionality
by filtering and displaying a list of products whose names contain
a specified search query. The search query is obtained from the GET
parameters of the request, and the results are rendered using the 'search.html' template.
"""
class SearchProduct(ListView):
    model = Product
    template_name = 'search.html'
    context_object_name = 'products'

    def get_queryset(self):
        search_products = self.request.GET.get('search_product')
        if search_products:
            products = Product.objects.filter(name__icontains = search_products)
            return products


"""
The view is designed to provide a RESTful API for managing comments,
including listing comments, creating new comments, updating existing comments,
and deleting comments while enforcing permissions to ensure that only authorized
users can perform these actions.
"""
class CommentView(APIView):
    def get(self, request):
        comments = Comment.objects.all()
        serializers_data = CommentSerializer(instance=comments, many=True)
        return Response(serializers_data.data, status=status.HTTP_200_OK)

    def post(self, request):
        comment_data = CommentSerializer(data=request.data)
        if comment_data.is_valid():
            comment_data.save()
            return Response(comment_data.data, status=status.HTTP_201_CREATED)
        return Response(comment_data.errors, status=status.HTTP_400_BAD_REQUEST)
    
    permission_classes = [IsOwnerOrReadOnly, ]
    def put(self, request, pk):
        comment_upd = Comment.objects.get(pk=pk)
        self.check_object_permissions(request, comment_upd)
        serializer_data = CommentSerializer(instance=comment_upd, data=request.data, partial=True)
        if serializer_data.is_valid():
            serializer_data.save()
            return Response(serializer_data.data, status=status.HTTP_201_CREATED)
        return Response(serializer_data.errors, status=status.HTTP_400_BAD_REQUEST)

    permission_classes = [IsOwnerOrReadOnly, ]
    def delete(self, request, pk):
        comment_dlt = Comment.objects.get(pk=pk)
        self.check_object_permissions(request, comment_dlt)
        comment_dlt.delete()
        return Response({'message': 'comment deleted...'}, status=status.HTTP_200_OK)
    

"""
This view is designed to display product details, including images and user comments,
and allows users to submit comments for products. It also checks whether the user
has ordered the product before, and if so, it allows the user to leave a comment.
"""
class ProductDetail(View):
    template_name = 'shop-details.html'
    form_class = UserComment

    def get(self, request, product_id):
        product_detail = Product.objects.filter(pk=product_id)
        img = ProductImage.objects.filter(product_id=product_id)
        comments = Comment.objects.filter(product_id=product_id, status=True)
        user_comment = False
        user_order = Order.objects.filter(user=request.user)
        if user_order.exists():
            for order in user_order:
                if OrderItems.objects.filter(order=order, product=product_id):
                    user_comment = True

        return render(request, self.template_name, {'product': product_detail,
                                                    'img': img, 'comment': user_comment,
                                                     'comments': comments, 'form':self.form_class})
    
    def post(self, request, product_id):
        comment_data = UserComment(request.POST)
        if comment_data.is_valid():
            product = Product.objects.get(id=product_id)
            user = request.user
            title = comment_data.cleaned_data['title']
            description = comment_data.cleaned_data['description']
            status = False

            comment = Comment(product_id=product, user=user, title=title, description=description, status=status)
            comment.save()
            
            product_detail = Product.objects.filter(pk=product_id)
            img = ProductImage.objects.filter(product_id=product_id)
            comments = Comment.objects.filter(product_id=product_id, status=True)
            user_comment = False
            user_order = Order.objects.filter(user=request.user)
            if user_order.exists():
                for order in user_order:
                    if OrderItems.objects.filter(order=order, product=product_id):
                        user_comment = True

            return render(request, self.template_name, {'product': product_detail,
                                                        'img': img, 'comment': user_comment,
                                                        'comments': comments, 'form':self.form_class})
        return render(request, 'index.html')

home/templates/inc/Header.html
{% load static %}

 <!-- Header Section Begin -->
 <header class="header">
    <div class="header__top">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-md-7">
                    <div class="header__top__left">
                        {% if request.user.is_authenticated %}
                        <p>{{ request.user.full_name }} Welcom to my online shope.</p>
                        {% else %}
                        <p>Welcom to my online shope.</p>
                        {% endif  %}
                    </div>
                </div>
                <div class="col-lg-6 col-md-5">
                    <div class="header__top__right">
                        <div class="header__top__links">
                            {% if request.user.is_authenticated %}
                            <a href="{% url 'accounts:user_logout' %}">Logout</a>
                            {% else %}
                            <a href="{% url 'accounts:user_login' %}">Login /</a>
                            <a href="{% url 'accounts:user_register' %}">Register</a>
                            {% endif %}
                        </div>
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-3">
                <div class="header__logo">
                    <a href=""><img src="{% static 'home/img/logos.png'%}" alt=""></a>
                </div>
            </div>
            <div class="col-lg-6 col-md-6">
                <nav class="header__menu mobile-menu">
                    <ul>
                        <li ><a href="{% url 'home:home' %}">Home</a></li>
                        <li><a href="{% url 'product:shop' %}">Shop</a></li>
                        <li><a href="#">Pages</a>
                            <ul class="dropdown">
                                <li><a href="{% url 'home:about' %}">About Us</a></li>
                                <li><a href="{% url 'order:shopping-cart' %}">Shopping Cart</a></li>
                                {% if request.user.is_authenticated %}
                                <li><a href="{% url 'order:checkout' %}">Check Out</a></li>
                                {% endif %}
                            </ul>
                        </li>
                        <li><a href="{% url 'home:contact' %}">Contacts</a></li>
                    </ul>
                </nav>
            </div>
            <div class="col-lg-3 col-md-3">
                <div class="header__nav__option">
                    {% if request.user.is_authenticated %}
                    <a href="{% url 'home:profile' %}"><img src="{% static 'home/img/icon/home.png' %}" ></a>
                    {% endif %}
                    <a href="#" class="search-switch"><img src="{% static 'home/img/icon/search.png' %}" ></a>
                    <a href="#"><img src="{% static 'home/img/icon/heart.png' %}" ></a>
                    <a href="{% url 'order:shopping-cart' %}"><img src="{% static 'home/img/icon/cart.png' %}"> <span id="product-count">{{ cart|length }}</span></a>
                </div>
            </div>
        </div>
        <div class="canvas__open"><i class="fa fa-bars"></i></div>
    </div>
</header>
<!-- Header Section End -->

<!-- Script section start -->
<script>
    var productCountCookie = getCookie('cart');
    if (productCountCookie !== null) {
        var itemCount = Object.keys(productCountCookie).length;
        document.getElementById('product-count').textContent = itemCount;
    }

    function getCookie(name) {
        var value = "; " + document.cookie;
        var parts = value.split("; " + name + "=");
        if (parts.length === 2) {
            return parts.pop().split(";").shift();
        }
        return null;
    }
</script>
<!-- Script section end -->

home/templates/inc/banner.html
{% load static %}
<!-- Banner Section Begin -->
<section class="banner spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-7 offset-lg-4">
                <div class="banner__item">
                    <div class="banner__item__pic">
                        <img src="{% static 'home/img/banner/banner-1.jpg' %}" alt="">
                    </div>
                    <div class="banner__item__text">
                        <h2>Clothing Collections 2030</h2>
                        <a href="#">Shop now</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-5">
                <div class="banner__item banner__item--middle">
                    <div class="banner__item__pic">
                        <img src="{% static 'home/img/banner/banner-2.jpg' %}" alt="">
                    </div>
                    <div class="banner__item__text">
                        <h2>Accessories</h2>
                        <a href="#">Shop now</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-7">
                <div class="banner__item banner__item--last">
                    <div class="banner__item__pic">
                        <img src="{% static 'home/img/banner/banner-3.jpg' %}" alt="">
                    </div>
                    <div class="banner__item__text">
                        <h2>Shoes Spring 2030</h2>
                        <a href="#">Shop now</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Banner Section End -->

home/templates/inc/hero.html
{% load static %}

 <!-- Hero Section Begin -->
 <section class="hero">
    <div class="hero__slider owl-carousel">
        <div class="hero__items set-bg" data-setbg="{% static 'home/img/hero/hero-1.jpg'%} ">
            <div class="container">
                <div class="row">
                    <div class="col-xl-5 col-lg-7 col-md-8">
                        <div class="hero__text">
                            <h6>Summer Collection</h6>
                            <h2>Fall - Winter Collections 2030</h2>
                            <p>A specialist label creating luxury essentials. Ethically crafted with an unwavering
                            commitment to exceptional quality.</p>
                            <a href="{% url 'product:shop' %}" class="primary-btn">Shop now <span class="arrow_right"></span></a>
                            <div class="hero__social">
                                <a href="https://github.com/Abbas-moradi"><i class="fa fa-facebook"></i></a>
                                <a href="https://github.com/Abbas-moradi"><i class="fa fa-twitter"></i></a>
                                <a href="https://github.com/Abbas-moradi"><i class="fa fa-pinterest"></i></a>
                                <a href="https://github.com/Abbas-moradi"><i class="fa fa-instagram"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="hero__items set-bg" data-setbg="{% static 'home/img/hero/hero-2.jpg' %}">
            <div class="container">
                <div class="row">
                    <div class="col-xl-5 col-lg-7 col-md-8">
                        <div class="hero__text">
                            <h6>Summer Collection</h6>
                            <h2>Fall - Winter Collections 2030</h2>
                            <p>A specialist label creating luxury essentials. Ethically crafted with an unwavering
                            commitment to exceptional quality.</p>
                            <a href="{% url 'product:shop' %}" class="primary-btn">Shop now <span class="arrow_right"></span></a>
                            <div class="hero__social">
                                <a href="#"><i class="fa fa-facebook"></i></a>
                                <a href="#"><i class="fa fa-twitter"></i></a>
                                <a href="#"><i class="fa fa-pinterest"></i></a>
                                <a href="#"><i class="fa fa-instagram"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Hero Section End -->

home/templates/inc/product.html
{% load static %}

  <!-- Product Section Begin -->
  <section class="product spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <ul class="filter__controls">
                    <li data-filter=".new-arrivals">New Arrivals</li>
                    <li data-filter=".hot-sales">Hot Sales</li>
                </ul>
            </div>
        </div>
        <div class="row product__filter">
            <div class="col-lg-3 col-md-6 col-sm-6 col-md-6 col-sm-6 mix hot-sales">
                <div class="shadow p-3 mb-5 bg-white rounded">
                    <div class="product__item">
                        <div class="product__item__pic set-bg" data-setbg="{{ most_ordered_product.image.url }}">
                            <ul class="product__hover">
                                <li><a href="#"><img src="{% static 'home/img/icon/heart.png' %}" alt=""></a></li>
                                <li><a href="#"><img src="{% static 'home/img/icon/compare.png' %}" alt=""></a></li>
                                <li><a href="#"><img src="{% static 'home/img/icon/search.png' %}" alt=""></a></li>
                            </ul>
                        </div>
                        <div class="product__item__text">
                            <a href="{% url 'product:product_detail' most_ordered_product.id %}"><h6>{{ most_ordered_product.name }} </h6></a>
                            {% if request.user.is_authenticated %}
                                <form method="post" action="{% url 'order:cart_add' most_ordered_product.id %}">
                                    {% csrf_token %}
                                    {{ form }}
                                    <input href="#" type="submit" value="+ Add To Cart" >
                                </form>
                            {% else %}
                                <a href="{% url 'accounts:user_login' %}" >Login first</a>
                            {% endif %}
                            <div class="rating">
                                <i class="fa fa-star-o"></i>
                                <i class="fa fa-star-o"></i>
                                <i class="fa fa-star-o"></i>
                                <i class="fa fa-star-o"></i>
                                <i class="fa fa-star-o"></i>
                            </div>
                            <h5>price .{{ most_ordered_product.price }} $</h5>
                            {% if most_ordered_product.number < 4 %}
                            <h5>left over .{{ most_ordered_product.number }}</h5>
                            {% else %}
                            <h5> .</h5>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
            {% for product in last_products %}
            <div class="col-lg-3 col-md-6 col-sm-6 col-md-6 col-sm-6 mix new-arrivals">
                <div class="shadow p-3 mb-5 bg-white rounded">
                    <div class="product__item">
                        <div class="product__item__pic set-bg" data-setbg="{{ product.image.url }}">
                            <ul class="product__hover">
                                <li><a href="#"><img src="{% static 'home/img/icon/heart.png' %}" alt=""></a></li>
                                <li><a href="#"><img src="{% static 'home/img/icon/compare.png' %}" alt=""></a></li>
                                <li><a href="#"><img src="{% static 'home/img/icon/search.png' %}" alt=""></a></li>
                            </ul>
                        </div>
                        <div class="product__item__text">
                            <a href="{% url 'product:product_detail' product.id %}"><h6>{{ product.name }} </h6></a>
                            {% if request.user.is_authenticated %}
                                <form method="post" action="{% url 'order:cart_add' product.id %}">
                                    {% csrf_token %}
                                    {{ form }}
                                    <input href="#" type="submit" value="+ Add To Cart" >
                                </form>
                            {% else %}
                                <a href="{% url 'accounts:user_login' %}" >Login first</a>
                            {% endif %}
                            <div class="rating">
                                <i class="fa fa-star-o"></i>
                                <i class="fa fa-star-o"></i>
                                <i class="fa fa-star-o"></i>
                                <i class="fa fa-star-o"></i>
                                <i class="fa fa-star-o"></i>
                            </div>
                            <h5>price .{{ product.price }} $</h5>
                            {% if product.number < 4 %}
                            <h5>left over .{{ product.number }}</h5>
                            {% else %}
                            <h5> .</h5>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
<!-- Product Section End -->

home/templates/inc/search.html
 <!-- Search Begin -->
 <div class="search-model">
    <div class="h-100 d-flex align-items-center justify-content-center">
        <div class="search-close-switch">+</div>
        <form class="search-model-form">
            <input type="text" id="search-input" placeholder="Search here.....">
        </form>
    </div>
</div>
<!-- Search End -->