OnlineShop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('order/', include('order.urls', namespace='order')),
    path('zarinpal/', include('zarinpal.urls', namespace='zarinpal')),
    path('product/', include('product.urls', namespace='product')),
    path('api_product/', include('product.urls', namespace='api_product')),
    path('api_accounts/', include('accounts.urls', namespace='api_accounts')),
    path('', include('home.urls',)),
    path('', include('api.urls',)),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views
from rest_framework.authtoken import views as auth_token
from rest_framework import routers


app_name = 'accounts'

urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='user_register'),
    path('verify/', views.UserRegisterVerifyCodeView.as_view(), name='verify_code'),
    path('login/', views.UsreLoginView.as_view(), name='user_login'),
    path('logout/', views.UserLogoutView.as_view(), name='user_logout'),
    path('address/', views.UserAddress.as_view(), name='user_address'),
    path('choice/', views.ChoiceAddress.as_view(), name='choice_address'),
    path('edit/', views.EditProfile.as_view(), name='edit_profile'),
    path('my_order/', views.MyOrder.as_view(), name='my_order'),
    path('user/', views.UserCreateView.as_view(), name='user-list-create'),
    path('hello/', views.HelloView.as_view(), name='hello'),
    path('api-token-auth/', auth_token.obtain_auth_token),
]

router = routers.SimpleRouter()
router.register('user', views.UserViewSet)
urlpatterns += router.urls

api/urls.py
from django.urls import path
from rest_framework import routers
from rest_framework.authtoken import views as auth_token
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

from api import views


app_name = 'api'

urlpatterns = [
    path('api-token-auth/', auth_token.obtain_auth_token),
    path('comment/', views.CommentView.as_view()),
    path('schema/', SpectacularAPIView.as_view(), name='schema'),
    path('swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
]

router = routers.SimpleRouter()
router.register('user', views.UserViewSet)
router.register('address', views.AddressViewSet)
router.register('order', views.OrderViewSet)
urlpatterns += router.urls

home/urls.py
from django.urls import path
from . import views
from product.views import *

app_name = 'home'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('contact/', views.Contact.as_view(), name='contact'),
    path('about/', views.About.as_view(), name='about'),
    path('details/', ProductDetail.as_view(), name='details'),
    path('profile/', UserProfile.as_view(), name='profile'),
]

accounts/forms.py
from django import forms
from .models import User, Address
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import ReadOnlyPasswordHashField


"""
This form is used to create a new user.
It collects information such as email, phone number, full name, and password. 
It also includes fields for password confirmation. In this form,
the clean_password2 method is defined for password validation.
"""
class UserCreationForm(forms.ModelForm):
    password1 = forms.CharField(label='password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='confirm password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('email', 'phone_number', 'full_name')

    def cleanpassword2(self):
        cd = self.cleaned_data
        if cd['password1'] and cd['password2'] and cd['password1'] != cd['password2']:
            raise ValidationError('passwords dont match')
        return cd['password2']
    
    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user


"""
This form is used to edit existing user information.
It allows the user to change email, phone number, full name, and password.
However, the password is displayed as a read-only field.
"""

class UserChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField(help_text='you can change password using <a href=\'../password/\'>this form</a>')

    class Meta:
        model = User
        fields = ('email', 'phone_number', 'full_name', 'password', 'last_login')

"""
These two forms are used for user registration. 
They collect information such as full name, email, phone number, and password.
Additionally, in both forms, the clean_email and clean_phone methods are defined
 to check for duplicate email and phone number entries.
"""

class UserRegisterForm(forms.Form):
    full_name = forms.CharField(label='full name')
    email = forms.EmailField()
    phone = forms.CharField(max_length=13)
    password = forms.CharField(widget=forms.PasswordInput)


class UserRegisterationForm(forms.Form):
    full_name = forms.CharField(label='full name')
    email = forms.EmailField()
    phone = forms.CharField(max_length=13)
    password = forms.CharField(widget=forms.PasswordInput)

    def clean_email(self):
        email = self.cleaned_data['email']
        user = User.objects.filter(email=email).exists()
        if user:
            raise ValidationError('this email already exists')
        return email
        
    def clean_phone(self):
        phone = self.cleaned_data['phone']
        user = User.objects.filter(phone_number=phone).exists()
        if user:
            raise ValidationError('this phone number already exists')
        return phone
    
"""
 This form is used for user login and includes fields
   for entering the phone number and password.
"""

class UserLoginForm(forms.Form):
    phone = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


"""
These two forms are used to verify a code sent to the user
for confirmation purposes (e.g., phone number verification).
They include an input field for entering the verification code.
"""

class VerifyCodeForm(forms.Form):
    code = forms.CharField()

class VerifyForm(forms.Form):
    code = forms.CharField()


"""
This form is used to create new addresses by users.
 It collects information such as province, city, street,
   and license plate number.
"""
class AddAddress(forms.Form):
    province = forms.CharField(max_length=100)
    city = forms.CharField(max_length=100)
    street = forms.CharField(max_length=100)
    license_plate = forms.IntegerField()


class AddressSelectionForm(forms.Form):
    address_id = forms.IntegerField(widget=forms.HiddenInput())
    main_address = forms.BooleanField(widget=forms.HiddenInput(), required=False)

accounts/views.py
from django.shortcuts import render, redirect
from django.views import View
from .forms import UserRegisterationForm, VerifyForm, UserRegisterForm, UserLoginForm
import random
from OnlineShop import settings
from utils import send_otp_code
from .models import OtpCode, User, Address
from django.contrib import messages
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated
from .serializers import UserSerializer, OtpCodeSerializer, AddressSerializer
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import AddAddress, AddressSelectionForm
from order.models import *
from rest_framework import viewsets, status
from django.shortcuts import get_object_or_404


"""
This view handles the user registration process,
 including form validation, code generation, 
 and session management.
"""
class UserRegisterView(View):
    template_name = 'register.html'
    form_class = UserRegisterForm

    def get(self, request):
        form = self.form_class
        return render(request, self.template_name, {'form':form})

    def post(self, request):
        form = UserRegisterForm(request.POST)
    
        if form.is_valid():
            random_code = random.randint(10000, 99999)
            send_otp_code(form.cleaned_data['phone'], random_code)
            print(random_code)
            OtpCode.objects.create(phone_number=form.cleaned_data['phone'], code=random_code)
            request.session['user_registration_info'] = {
                'full_name': form.cleaned_data['full_name'],
                'email': form.cleaned_data['email'],
                'phone': form.cleaned_data['phone'],
                'password': form.cleaned_data['password'],
            }
            messages.success(request, 'code sending for you')
            return redirect('accounts:verify_code')
        
        return render(request, 'verify.html', {'form':form})

"""
This view handles the code verification process during user
registration and creates a new user account upon successful verification.
It also manages error messages and redirects as needed.
"""
class UserRegisterVerifyCodeView(View):
    form_class = VerifyForm

    def get(self, request):
        form = self.form_class
        return render(request, 'verify.html', {'form':form})

    def post(self, request):
        user_session = request.session['user_registration_info']
        otp_code_instance = OtpCode.objects.get(phone_number=user_session['phone'])
        form = VerifyForm(request.POST)
        
        if form.is_valid():
            cd = form.cleaned_data
            if int(cd['code']) == int(otp_code_instance.code):
                User.objects.create_user(
                    user_session['phone'],
                    user_session['email'],
                    user_session['full_name'],
                    user_session['password']
                )

                otp_code_instance.delete()

                messages.success(request, 'register success', 'success')
                return redirect('home:home')
            else:
                messages.error(request, 'this code is wrong', 'danger')
                return redirect('accounts:verify_code')
        return redirect('home:home')
    
    
"""
These views handle user login and logout operations and provide
a seamless authentication process for users in my Django application.
"""
class UsreLoginView(View):
    form_class = UserLoginForm
    template_name = 'user_login.html'

    def get(self, request):
        form = self.form_class
        return render(request, self.template_name, {'form':form})
    
    def post(self,request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            phone = cd['phone']
            password = cd['password']
            user = authenticate(request, phone_number=phone, password=password)
            if user is not None:
                login(request, user)
                return redirect('home:home')
            messages.error(request, 'phone or pass is wrong', 'warning')
        return render(request, self.template_name, {'form':form})

class UserLogoutView(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        return redirect('home:home')
            

class UserCreateView(APIView):

    def get(self, request):
        queryset = User.objects.all()
        serializer_class = UserSerializer(instance=queryset, many=True)
        return Response(serializer_class.data)


class HelloView(APIView):
    permission_classes = (IsAuthenticated,)

    def get(self, request):
        content = {'message': 'Hello, World!'}
        return Response(content)
    
class UserAddress(View):
    template_name = 'address.html'
    form_class = AddAddress
    choice_address = AddressSelectionForm

    def get(self, request):
        user_address = Address.objects.filter(user=request.user)
        return render(request, self.template_name, {'form':self.form_class, 'user_address': user_address, 'choice_form': self.choice_address})
    
    def post(self, request):
        # user_address_exist = Address.objects.filter(user=request.user)
        # if user_address_exist:
        #     user_address_exist.delete()

        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            Address.objects.create(
                user=request.user, province=cd['province'],
                city=cd['city'], street=cd['street'],
                license_plate=cd['license_plate']
                )
            return redirect('home:home')
        return render(request, self.template_name, {'form':self.form_class})
    

class ChoiceAddress(View):
    form_class = AddressSelectionForm

    def post(self, request):
        form = AddressSelectionForm(request.POST)
        address_id = form['address_id']
        if form.is_valid():
            user_addresses = Address.objects.filter(user=request.user)
            selected_address_id = form.cleaned_data['address_id']
            for address in user_addresses:
                if address.id == selected_address_id:
                    address.main_address = True
                    address.save()
                else:
                    address.main_address = False
                    address.save()
            return redirect('home:profile')
        return redirect('home:home')
    
class EditProfile(View):
    template = 'edit_profile.html'
    form = UserRegisterForm

    def get(self, request):
        current_user = request.user
        return render(request, self.template, {'form':self.form,'user':current_user})
    

class MyOrder(View):
    template_name = 'my_order.html'

    def get(self, request):
        user_order = Order.objects.filter(user=request.user)
        user_order_item = OrderItems.objects.filter(order__in=user_order)
        return render(request, self.template_name, {'orders':user_order, 'items':user_order_item})



"""
This UserViewSet provides a RESTful API for managing user data,
including creating, retrieving, updating, and deactivating user accounts.
It also enforces authentication for these operations, ensuring that only 
authenticated users can access these endpoints.
"""
class UserViewSet(viewsets.ViewSet):
    permission_classes = [IsAuthenticated, ]
    queryset = User.objects.all()

    def list(self, request):
        serializer_data = UserSerializer(instance=self.queryset, many=True)
        return Response(data= serializer_data.data)

    def create(self, request):
        serializer_data = UserSerializer(data=request.POST)
        if serializer_data.is_valid():
            serializer_data.save()
            return Response(data= serializer_data.data, status=status.HTTP_201_CREATED)
        return Response(serializer_data.errors, status=status.HTTP_400_BAD_REQUEST)

    def retrieve(self, request, pk=None):
        user = get_object_or_404(self.queryset, pk=pk)
        serializer_data = UserSerializer(instance=user)
        return Response(data= serializer_data.data, status=status.HTTP_200_OK)

    def partial_update(self, request, pk=None):
        user = get_object_or_404(self.queryset, pk=pk)
        serializer_data = UserSerializer(instance=user, data=request.POST, partial=True)
        if serializer_data.is_valid():
            serializer_data.save()
            return Response(data= serializer_data.data, status=status.HTTP_206_PARTIAL_CONTENT)
        return Response(serializer_data.errors, status=status.HTTP_400_BAD_REQUEST)

    def destroy(self, request, pk=None):
        user = get_object_or_404(self.queryset, pk=pk)
        user.is_active = False
        user.save()
        return Response({'result': 'user deactivated now...'}, status=status.HTTP_200_OK)
    

accounts/templates/address.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Male_Fashion Template">
    <meta name="keywords" content="Male_Fashion, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Male-Fashion | Template</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@300;400;600;700;800;900&display=swap"
    rel="stylesheet">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <!-- Css Styles -->
    <link rel="stylesheet" href="{% static 'home/css/bootstrap.min.css' %}" rel="stylesheet"> 
    <link rel="stylesheet" href="{% static 'home/css/font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'home/css/elegant-icons.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'home/css/magnific-popup.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'home/css/nice-select.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'home/css/owl.carousel.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'home/css/slicknav.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'home/css/style.css' %}" type="text/css">
</head>

<body>
    {% include 'inc/Header.html' %}

    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-option">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb__text">
                        <h4>Address</h4>
                        <div class="breadcrumb__links">
                            <a href="./index.html">Home</a>
                            <a href="./shop.html">Profile</a>
                            <span>Address</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- Checkout Section Begin -->
    <section class="checkout spad">
        <div class="container">
            <h4>User addresses</h4></br>
            <form method="post" action="{% url 'accounts:choice_address' %}">
            {% csrf_token %}
            {% for address in user_address %}
                <h5>
                    <label>
                        <input type="radio" name="address_id" value="{{ address.id }}" {% if address.main_address %}checked{% endif %}>
                        <input type="hidden" name="main_address" value="{{ is_main_address }}">
                        {{ address }}
                    </label><br>
                </h5>
            {% endfor %}
            <button type="submit">choice main address</button><br>
        </form>
        </br>
            <div class="checkout__form">
                    <div class="row">
                        <div class="col-lg-8 col-md-6">
                            <h6 class="coupon__code"><span class="icon_tag_alt"></span> Enter your address accurately</h6>
                            <h6 class="checkout__title">Address Details</h6>
                            <div class="row">
                            <form method="post" action="{% url 'accounts:user_address' %}">
                                {% csrf_token %}
                                <div class="col-lg-6">
                                    <div class="checkout__input">
                                        <p>Province<span>*</span></p>
                                        <input name="province" type="text">
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="checkout__input">
                                        <p>City<span>*</span></p>
                                        <input name="city" type="text">
                                    </div>
                                </div>
                            </div>
                            <div class="checkout__input">
                                <p>Street<span>*</span></p>
                                <input name="street" type="text">
                            </div>
                            <div  class="checkout__input">
                                <p>License_plate<span>*</span></p>
                                <input name="license_plate" type="text">
                            </div>
                            
                            <div class="button input-box">
                                <button type="submit" class="primary-btn">Add Address</button>
                            </div>
                        </form>
                        
                        </div>      
                    </div>
            </div>
        </div>
    </section>
    <!-- Checkout Section End -->

    <!-- Footer Section Begin -->
    <footer class="footer">
        <div class="row">
            <div class="col-lg-12 text-center">
                <div class="footer__copyright__text">
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    <p>Copyright ©
                        <script>
                            document.write(new Date().getFullYear());
                        </script>-2020
                        This online store template was created<i class="fa fa-heart-o"
                        aria-hidden="true"></i> by <a href="https://github.com/Abbas-moradi" target="_blank">Abbas Moradi</a>
                    </p>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </div>
            </div>
        </div>
    </footer>
    <!-- Footer Section End -->

    <!-- Search Begin -->
    <div class="search-model">
        <div class="h-100 d-flex align-items-center justify-content-center">
            <div class="search-close-switch">+</div>
            <form class="search-model-form">
                <input type="text" id="search-input" placeholder="Search here.....">
            </form>
        </div>
    </div>
    <!-- Search End -->

    <!-- Js Plugins -->
    <script src="{% static 'home/js/jquery-3.3.1.min.js'%}"></script>
    <script src="{% static 'home/js/bootstrap.min.js'%}"></script>
    <script src="{% static 'home/js/jquery.nice-select.min.js'%}"></script>
    <script src="{% static 'home/js/jquery.nicescroll.min.js'%}"></script>
    <script src="{% static 'home/js/jquery.magnific-popup.min.js'%}"></script>
    <script src="{% static 'home/js/jquery.countdown.min.js'%}"></script>
    <script src="{% static 'home/js/jquery.slicknav.js'%}"></script>
    <script src="{% static 'home/js/mixitup.min.js'%}"></script>
    <script src="{% static 'home/js/owl.carousel.min.js'%}"></script>
    <script src="{% static 'home/js/main.js'%}"></script>
 
</body>

</html>

accounts/templates/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Male_Fashion Template">
    <meta name="keywords" content="Male_Fashion, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Online Shope | Fashion</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@300;400;600;700;800;900&display=swap"
    rel="stylesheet">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <!-- Css Styles -->
    <link rel="stylesheet" href="{% static 'home/css/bootstrap.min.css' %}" rel="stylesheet"> 
    <link rel="stylesheet" href="{% static 'home/css/font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'home/css/elegant-icons.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'home/css/magnific-popup.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'home/css/nice-select.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'home/css/owl.carousel.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'home/css/slicknav.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'home/css/style.css' %}" type="text/css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

</head>

<body>
    {% include 'inc/Header.html' %}
    <div class="container">
      <div class="row">
          <div class="col-md-2">
              <a class="btn btn-secondary bg-blue mb-3" href="{% url 'accounts:edit_profile' %}">My Profile</a>
              <a class="btn btn-secondary bg-blue mb-3" href="{% url 'accounts:my_order' %}">My Order</a>
              <a class="btn btn-secondary" href="{% url 'accounts:user_address' %}">Add Address</a>
          </div>
          <div class="col-md-6">
              {% if last_order %}
              <div class="card">
                <img src="{% static 'home/img/icon/cart.png' %}" class="card-img-top" width="19px" height="19px">

                  <div class="card-body">
                      <h5 class="card-title">Latest Order</h5>
                      <p class="card-text">You can see your latest purchase invoice here</p>
                      <h4>Order Items:</h4>
                      {% for order in orders %}
                      <h6># {{ order.product }} - $ {{ order.price }} - & {{ order.quantity }}</h6>
                      {% endfor %}
                  </div>
                  <div class="card-footer">
                      <small class="text-body-secondary">{{ last_order.order_date }}</small>
                  </div>
              </div>
              {% endif %}
          </div>
      </div>
  </div>
</br></br></br>
  
      
    
    

    <!-- Footer Section Begin -->
    <footer class="footer">
        <div class="row">
            <div class="col-lg-12 text-center">
                <div class="footer__copyright__text">
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    <p>Copyright ©
                        <script>
                            document.write(new Date().getFullYear());
                        </script>-2020
                        This online store template was created<i class="fa fa-heart-o"
                        aria-hidden="true"></i> by <a href="https://github.com/Abbas-moradi" target="_blank">Abbas Moradi</a>
                    </p>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </div>
            </div>
        </div>
    </footer>
    <!-- Footer Section End -->

    <!-- Search Begin -->
    <div class="search-model">
        <div class="h-100 d-flex align-items-center justify-content-center">
            <div class="search-close-switch">+</div>
            <form class="search-model-form">
                <input type="text" id="search-input" placeholder="Search here.....">
            </form>
        </div>
    </div>
    <!-- Search End -->

    <!-- Js Plugins -->
    <script src="{% static 'home/js/jquery-3.3.1.min.js'%}"></script>
    <script src="{% static 'home/js/bootstrap.min.js'%}"></script>
    <script src="{% static 'home/js/jquery.nice-select.min.js'%}"></script>
    <script src="{% static 'home/js/jquery.nicescroll.min.js'%}"></script>
    <script src="{% static 'home/js/jquery.magnific-popup.min.js'%}"></script>
    <script src="{% static 'home/js/jquery.countdown.min.js'%}"></script>
    <script src="{% static 'home/js/jquery.slicknav.js'%}"></script>
    <script src="{% static 'home/js/mixitup.min.js'%}"></script>
    <script src="{% static 'home/js/owl.carousel.min.js'%}"></script>
    <script src="{% static 'home/js/main.js'%}"></script>
 
</body>

</html>

accounts/templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="UTF-8">
    <!--<title> Login and Registration Form in HTML & CSS | CodingLab </title>-->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- Fontawesome CDN Link -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
   </head>
<body>
  <div class="container">
    <input type="checkbox" id="flip">
    <div class="cover">
      <div class="front">
        <img src="{% static 'img/frontImg.jpg' %}" alt="">
        <div class="text">
          <span class="text-1">Every new friend is a <br> new adventure</span>
          <span class="text-2">Let's get connected</span>
        </div>
      </div>
      <div class="back">
        <img class="backImg" src="{% static 'img/backImg.jpg' %}" alt="">
        <div class="text">
          <span class="text-1">Complete miles of journey <br> with one step</span>
          <span class="text-2">Let's get started</span>
        </div>
      </div>
    </div>
    <div class="forms" for="flip">
        <div class="form-content">
          <div class="login-form">
            <div class="title">Register</div>
          <form method="post" action="">
          {% csrf_token %}
            <div class="input-boxes">
              <div class="input-box">
                <i class="fas fa-user"></i>
                <input class="form-control" name="full_name" type="text" placeholder="Enter your full name" required>
              </div>
              <div class="input-box">
                <i class="fas fa-envelope"></i>
                <input class="form-control" name="email" type="text" placeholder="Enter your email" required>
              </div>
              <div class="input-box">
                <i class="fas fa-phone"></i>
                <input class="form-control" name="phone" type="text" placeholder="Enter your phone" required>
              </div>
              <div class="input-box">
                <i class="fas fa-lock"></i>
                <input class="form-control" name="password" type="password" placeholder="Enter your password" required>
              </div>
              <div class="button input-box">
                <input type="submit" value="Register" id="registration">
              </div>
              <div class="text sign-up-text">Already have an account? <a href="{% url 'accounts:user_login' %}">Login now</label></div>
              <div class="text sign-up-text">back to <a href="{% url 'home:home' %}">home</a></div>
            </div>
      </form>
    </div>
  </div>
    </div>
  </div>
</body>
</html>